app:
  name: Tallink conference
  description: "Tallink conference api"
  version: "0.0.1"

api:
  version: v1
  prefix: /api/public

authentication:
  key: "d3b6681900dd39068483c3a0decad73fbe42acb363fb55babb87a74b22d6aac5"
  access-token-validity-seconds: 3600
  refresh-token-validity-seconds: 2592000
  users:
    -
      user: "Admin"
      password: "$2a$10$lSPgvAPfxWNLbXoMqQpkZe5jlxdtsQArfIwwnQYWsZFt7lZvPd0QS"
      role: ROLE_ADMIN

java:
  version: 1.8

security:
  oauth2:
    resource:
      filter-order: 3

spring:
  main.banner-mode: "off"
  application.name: ${app.name}
  output.ansi.enabled: always
  datasource:
    url: jdbc:h2:mem:app_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
  use-forward-headers: true
  compression:
    enabled: true
    min-response-size: 8192
    mime-types:
      - application/json
      - text/html
      - text/css
      - application/javascript

management.security.enabled: false

